### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by Zakarialabib** [laravelmorocco/laravelmaroc.com#18]
../dashboard/threads page has an issue , 

`
[2023-07-23 21:46:03] production.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1055 'laravelm_db_432.threads.user_id' isn't in GROUP BY (SQL: select count(*) as aggregate from (select `threads`.*, 
                CASE WHEN COALESCE(MAX(replies.created_at), 0) > threads.created_at
                THEN COALESCE(MAX(replies.created_at), 0)
                ELSE threads.created_at
                END AS latest_creation
             from `threads` left join `replies` on `threads`.`id` = `replies`.`replyable_id` and `replies`.`replyable_type` = App\Models\Thread where `threads`.`user_id` = 1 and `threads`.`user_id` is not null group by `threads`.`id`) as `aggregate_table`) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 'laravelm_db_432.threads.user_id' isn't in GROUP BY (SQL: select count(*) as aggregate from (select `threads`.*, 
                CASE WHEN COALESCE(MAX(replies.created_at), 0) > threads.created_at
                THEN COALESCE(MAX(replies.created_at), 0)
                ELSE threads.created_at
                END AS latest_creation
             from `threads` left join `replies` on `threads`.`id` = `replies`.`replyable_id` and `replies`.`replyable_type` = App\\Models\\Thread where `threads`.`user_id` = 1 and `threads`.`user_id` is not null group by `threads`.`id`) as `aggregate_table`) at /home2/laravelm/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[stacktrace]
`

`
[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 'laravelm_db_432.threads.user_id' isn't in GROUP BY at /home2/laravelm/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414)
`

**Comment by faissaloux** [comment]
I couldn't reproduce this, can you give more details on how to reproduce?
