### ISSUE TITLE
`dependabot-auto-merge` wokflow can't auto merge

### ISSUE THREAD

**Issue by faissaloux** [laravelmorocco/laravelmaroc.com#29]
![Screenshot from 2023-07-25 21-39-32](https://github.com/laravelmorocco/laravelmaroc.com/assets/60013703/e9225254-ebb0-4bd9-b952-eee608bd61fb)

You need to enable `Allow auto-merge` from Settings.

**Comment by Zakarialabib** [comment]
its enabled now
