### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Zakarialabib** [laravelmorocco/laravelmaroc.com#31]
![Image](https://user-images.githubusercontent.com/58374576/255428077-a2889fc1-0447-4984-99c6-ec83ceba52b0.png)

**Comment by Zakarialabib** [comment]
i made a miskate by pushing it directly to main, x) 
anyway , we should preview the new logo discussed to see how it looks

**Comment by ismaail** [comment]
in the project settings, you can make the **main** branch **protected** to avoid accidental push.
