### ISSUE TITLE
Unable to find the feature.

### ISSUE THREAD

**Issue by ismaail** [laravelmorocco/laravelmaroc.com#32]
After finishing all the steps from the README, i got this error:

`LaravelFeature\Domain\Exception\FeatureException`

**Unable to find the feature.**

![image](https://github.com/laravelmorocco/laravelmaroc.com/assets/4411670/0ceb2bd9-715a-435b-8ef6-4ae8f8f4c658)

**Comment by faissaloux** [comment]
Can you specify the steps you followed?

**Comment by ismaail** [comment]
@faissaloux  steps followed:

1. clone the project repo
2. copy `.env.example.com` to `.env`
3. run migrations
4. run `php artisan db:seed --class=DummyDatabaseSeeder`

**Comment by faissaloux** [comment]
Here are the steps you need to follow: https://github.com/laravelmorocco/laravelmaroc.com#installation

**Comment by faissaloux** [comment]
@ismaail Any updates!

**Comment by ismaail** [comment]
@faissaloux I tried again, same error

**Comment by ismaail** [comment]
Issue solved by adding a new record to the **features** table with this values:

- name = `premium`
- is_enabled = `1`

I don't know why the `FeatureTableSeeder` don't exectue when I run `php artisan db:seed`

**Comment by faissaloux** [comment]
Did you run `composer setup` ? It's the step you missed.

**Comment by ismaail** [comment]
yes, follwed all the steps from the README file

**Comment by faissaloux** [comment]
All seeders succeeded with no error? If some error appeared can you show it to me.

**Comment by ismaail** [comment]
There a problem with `db:seed`, calling Seeder stops after `WorldSeeder`

![image](https://github.com/laravelmorocco/laravelmaroc.com/assets/4411670/38ba00a3-be49-4c43-8cce-326b0e2fa7bb)

I solved the issue in [PR#33](https://github.com/laravelmorocco/laravelmaroc.com/pull/33)
